from __future__ import annotations

import json
from pathlib import Path
from types import SimpleNamespace

import pytest
import yaml

from app.training.candidate_builder import build_cycle_candidate_from_proposals
from app.training.proposal_store import (
    list_cycle_proposal_bundles,
    load_cycle_proposal_bundle,
    persist_cycle_proposal_bundle,
)
from app.training.suggestion_tracking import (
    evaluate_proposal_effect,
    refresh_cycle_history_suggestion_effects,
)
from config import PROJECT_ROOT
from invest.evolution import YamlConfigMutator


class Event:
    def __init__(self, **kwargs):
        self.cycle_id = kwargs.get("cycle_id")
        self.trigger = kwargs["trigger"]
        self.stage = kwargs["stage"]
        self.status = kwargs.get("status", "ok")
        self.decision = dict(kwargs.get("decision", {}))
        self.applied_change = dict(kwargs.get("applied_change", {}))
        self.lineage = dict(kwargs.get("lineage", {}))
        self.evidence = dict(kwargs.get("evidence", {}))
        self.notes = kwargs.get("notes", "")

    def to_dict(self):
        return {
            "cycle_id": self.cycle_id,
            "trigger": self.trigger,
            "stage": self.stage,
            "status": self.status,
            "decision": dict(self.decision),
            "applied_change": dict(self.applied_change),
            "lineage": dict(self.lineage),
            "evidence": dict(self.evidence),
            "notes": self.notes,
        }


def _proposal(
    proposal_id: str,
    *,
    source: str,
    patch: dict,
    proposal_kind: str,
    cycle_id: int = 7,
    target_scope: str = "candidate",
) -> dict:
    return {
        "proposal_id": proposal_id,
        "cycle_id": cycle_id,
        "source": source,
        "target_scope": target_scope,
        "patch": dict(patch),
        "rationale": f"generated by {source}",
        "evidence": {},
        "metadata": {"proposal_kind": proposal_kind},
        "active_params_snapshot": {"position_size": 0.2},
        "created_at": "2026-03-16T00:00:00",
    }


def _repo_model_config(name: str) -> str:
    return str((PROJECT_ROOT / "invest" / "models" / "configs" / name).resolve())


def test_proposal_store_persists_cycle_bundle_and_supports_roundtrip(tmp_path: Path):
    controller = SimpleNamespace(
        output_dir=tmp_path,
        current_cycle_learning_proposals=[
            _proposal(
                "proposal_0007_001",
                source="optimization.llm_analysis",
                patch={"position_size": 0.16},
                proposal_kind="runtime_param_adjustment",
            ),
            _proposal(
                "proposal_0007_002",
                source="review.agent_weight_adjustment",
                patch={"trend_hunter": 0.9},
                proposal_kind="agent_weight_adjustment",
            ),
        ],
    )

    bundle = persist_cycle_proposal_bundle(
        controller,
        cycle_id=7,
        execution_snapshot={
            "active_config_ref": "invest/models/configs/momentum_v1.yaml",
            "active_version_id": "version_active_1",
            "runtime_fingerprint": "fingerprint_active_1",
            "model_name": "momentum",
        },
    )

    assert Path(bundle["bundle_path"]).exists()
    assert bundle["proposal_ids"] == ["proposal_0007_001", "proposal_0007_002"]
    assert bundle["suggestion_tracking_summary"]["suggestion_count"] == 2
    assert bundle["suggestion_tracking_summary"]["queued_suggestion_count"] == 2

    loaded = load_cycle_proposal_bundle(bundle["bundle_path"])
    listed = list_cycle_proposal_bundles(tmp_path)

    assert loaded["proposal_bundle_id"] == bundle["proposal_bundle_id"]
    assert loaded["active_version_id"] == "version_active_1"
    assert loaded["runtime_fingerprint"] == "fingerprint_active_1"
    assert loaded["proposals"][0]["suggestion_id"] == "suggestion_0007_001"
    assert loaded["proposals"][0]["adoption_status"] == "queued"
    assert loaded["proposals"][0]["effect_status"] == "pending_adoption"
    assert listed[0]["proposal_bundle_id"] == bundle["proposal_bundle_id"]


def test_candidate_builder_merges_review_and_optimization_proposals_into_single_candidate(tmp_path: Path):
    config_path = _repo_model_config("momentum_v1.yaml")
    appended = []
    logs = []
    controller = SimpleNamespace(
        output_dir=tmp_path,
        model_name="momentum",
        model_config_path=config_path,
        auto_apply_mutation=False,
        current_params={"position_size": 0.2, "take_profit_pct": 0.15},
        current_cycle_learning_proposals=[
            _proposal(
                "proposal_0007_001",
                source="optimization.llm_analysis",
                patch={"position_size": 0.12},
                proposal_kind="runtime_param_adjustment",
            ),
            _proposal(
                "proposal_0007_002",
                source="optimization.llm_scoring",
                patch={"weights": {"change_5d": 0.25}},
                proposal_kind="scoring_adjustment",
            ),
            _proposal(
                "proposal_0007_003",
                source="review.agent_weight_adjustment",
                patch={"trend_hunter": 0.9},
                proposal_kind="agent_weight_adjustment",
            ),
            _proposal(
                "proposal_0007_004",
                source="review.param_adjustment",
                patch={"position_size": 0.14},
                proposal_kind="param_adjustment",
            ),
        ],
        model_mutator=YamlConfigMutator(generations_dir=tmp_path / "generations"),
        cycle_history=[],
        _append_optimization_event=lambda event: appended.append(event.to_dict()),
        _emit_module_log=lambda *args, **kwargs: logs.append((args, kwargs)),
        _reload_investment_model=lambda path: None,
    )
    bundle = persist_cycle_proposal_bundle(
        controller,
        cycle_id=7,
        execution_snapshot={
            "active_config_ref": config_path,
            "active_version_id": "version_active_1",
            "runtime_fingerprint": "fingerprint_active_1",
            "model_name": "momentum",
        },
    )

    event = build_cycle_candidate_from_proposals(
        controller,
        cycle_id=7,
        proposal_bundle=bundle,
        event_factory=Event,
        trigger_reason="cycle_review_completed",
    )
    payload = event.to_dict()
    candidate_path = Path(payload["decision"]["config_path"])
    generated = yaml.safe_load(candidate_path.read_text(encoding="utf-8"))

    assert payload["stage"] == "candidate_build"
    assert payload["decision"]["proposal_bundle_id"] == bundle["proposal_bundle_id"]
    assert payload["lineage"]["candidate_config_ref"] == str(candidate_path)
    assert payload["applied_change"]["proposal_refs"] == [
        "proposal_0007_003",
        "proposal_0007_004",
    ]
    assert generated["params"]["position_size"] == 0.14
    assert generated["summary_scoring"]["weights"]["change_5d"] == 0.15
    assert generated["agent_weights"]["trend_hunter"] == 0.9
    assert appended[-1]["stage"] == "candidate_build"
    assert any(kwargs.get("kind") == "candidate_build" for _, kwargs in logs)
    gate = payload["evidence"]["proposal_gate"]
    assert gate["proposal_summary"]["approved_proposal_count"] == 2
    assert gate["proposal_summary"]["blocked_proposal_count"] == 2
    assert set(gate["proposal_summary"]["top_block_reasons"]) == {
        "single_step_identity_drift_exceeded",
        "single_step_scoring_identity_drift_exceeded",
    }
    assert gate["blocked_proposals"][0]["proposal_id"] == "proposal_0007_001"
    assert gate["approved_proposals"][-1]["proposal_id"] == "proposal_0007_004"
    tracked_bundle = load_cycle_proposal_bundle(bundle["bundle_path"])
    assert tracked_bundle["suggestion_tracking_summary"]["adopted_suggestion_count"] == 2
    assert tracked_bundle["suggestion_tracking_summary"]["rejected_suggestion_count"] == 2
    tracked_by_id = {
        item["proposal_id"]: item
        for item in tracked_bundle["proposals"]
    }
    assert tracked_by_id["proposal_0007_003"]["adoption_status"] == "adopted_to_candidate"
    assert tracked_by_id["proposal_0007_003"]["effect_status"] == "pending"
    assert tracked_by_id["proposal_0007_001"]["adoption_status"] == "rejected_by_proposal_gate"
    assert tracked_by_id["proposal_0007_001"]["effect_status"] == "not_applicable"


def test_candidate_builder_skips_new_candidate_when_pending_candidate_exists(tmp_path: Path):
    controller = SimpleNamespace(
        output_dir=tmp_path,
        model_name="momentum",
        model_config_path=_repo_model_config("momentum_v1.yaml"),
        auto_apply_mutation=False,
        current_params={"position_size": 0.2},
        current_cycle_learning_proposals=[
            _proposal(
                "proposal_0008_001",
                source="optimization.llm_analysis",
                patch={"position_size": 0.16},
                proposal_kind="runtime_param_adjustment",
                cycle_id=8,
            ),
        ],
        model_mutator=YamlConfigMutator(generations_dir=tmp_path / "generations"),
        cycle_history=[
            SimpleNamespace(
                cycle_id=7,
                lineage_record={
                    "deployment_stage": "candidate",
                    "lineage_status": "candidate_pending",
                    "candidate_config_ref": str(tmp_path / "pending_candidate.yaml"),
                },
            )
        ],
        _append_optimization_event=lambda event: None,
        _emit_module_log=lambda *args, **kwargs: None,
        _reload_investment_model=lambda path: None,
    )
    bundle = persist_cycle_proposal_bundle(
        controller,
        cycle_id=8,
        execution_snapshot={
            "active_config_ref": controller.model_config_path,
            "active_version_id": "version_active_1",
            "runtime_fingerprint": "fingerprint_active_1",
            "model_name": "momentum",
        },
    )

    event = build_cycle_candidate_from_proposals(
        controller,
        cycle_id=8,
        proposal_bundle=bundle,
        event_factory=Event,
        trigger_reason="cycle_review_completed",
    )
    payload = event.to_dict()

    assert payload["stage"] == "candidate_build_skipped"
    assert payload["decision"]["pending_candidate_ref"].endswith("pending_candidate.yaml")
    assert payload["lineage"]["deployment_stage"] == "candidate"
    tracked_bundle = load_cycle_proposal_bundle(bundle["bundle_path"])
    assert tracked_bundle["suggestion_tracking_summary"]["deferred_suggestion_count"] == 1
    assert tracked_bundle["proposals"][0]["adoption_status"] == "deferred_pending_candidate"
    assert tracked_bundle["proposals"][0]["effect_status"] == "pending_adoption"


def test_evaluate_proposal_effect_marks_improved_after_window():
    proposal = {
        "proposal_id": "proposal_0004_001",
        "suggestion_id": "suggestion_0004_001",
        "cycle_id": 4,
        "source": "review.param_adjustment",
        "patch": {"position_size": 0.14},
        "metadata": {"proposal_kind": "param_adjustment"},
        "adoption_status": "adopted_to_candidate",
        "adoption_ref": {"decision_cycle_id": 4},
        "effect_window": {
            "window_cycles": 3,
            "start_cycle_id": 5,
            "end_cycle_id": 7,
            "evaluation_after_cycle_id": 7,
        },
        "effect_target_metrics": ["avg_return_pct", "benchmark_pass_rate"],
        "effect_status": "pending",
        "effect_result": {"status": "pending", "observed_cycles": 0, "summary": ""},
    }
    cycle_history = [
        {"cycle_id": 2, "return_pct": -0.8, "benchmark_passed": False},
        {"cycle_id": 3, "return_pct": -0.2, "benchmark_passed": False},
        {"cycle_id": 4, "return_pct": 0.1, "benchmark_passed": False},
        {"cycle_id": 5, "return_pct": 1.2, "benchmark_passed": True},
        {"cycle_id": 6, "return_pct": 0.9, "benchmark_passed": True},
        {"cycle_id": 7, "return_pct": 0.8, "benchmark_passed": True},
    ]

    evaluated = evaluate_proposal_effect(
        proposal,
        cycle_history=cycle_history,
        current_cycle_id=7,
    )

    assert evaluated["effect_status"] == "improved"
    assert evaluated["effect_result"]["status"] == "improved"
    assert evaluated["effect_result"]["observed_cycles"] == 3
    assert {
        item["metric"] for item in evaluated["effect_result"]["metric_results"]
    } == {"avg_return_pct", "benchmark_pass_rate"}


def test_refresh_cycle_history_suggestion_effects_updates_bundle_tracking(tmp_path: Path):
    bundle_path = tmp_path / "proposal_store" / "cycle_0004_demo.json"
    bundle_path.parent.mkdir(parents=True, exist_ok=True)
    bundle = {
        "schema_version": "training.proposal_bundle.v1",
        "proposal_bundle_id": "proposal_bundle_0004_demo",
        "cycle_id": 4,
        "proposals": [
            {
                "proposal_id": "proposal_0004_001",
                "suggestion_id": "suggestion_0004_001",
                "cycle_id": 4,
                "source": "review.param_adjustment",
                "patch": {"position_size": 0.14},
                "metadata": {"proposal_kind": "param_adjustment"},
                "adoption_status": "adopted_to_candidate",
                "adoption_ref": {"decision_cycle_id": 4},
                "effect_window": {
                    "window_cycles": 2,
                    "start_cycle_id": 5,
                    "end_cycle_id": 6,
                    "evaluation_after_cycle_id": 6,
                },
                "effect_target_metrics": ["avg_return_pct"],
                "effect_status": "pending",
                "effect_result": {"status": "pending", "observed_cycles": 0, "summary": ""},
            }
        ],
    }
    bundle_path.write_text(json.dumps(bundle, ensure_ascii=False, indent=2), encoding="utf-8")
    cycle_history = [
        SimpleNamespace(
            cycle_id=4,
            return_pct=0.1,
            benchmark_passed=False,
            proposal_bundle={**bundle, "bundle_path": str(bundle_path)},
        ),
        SimpleNamespace(cycle_id=5, return_pct=0.6, benchmark_passed=True, proposal_bundle={}),
        SimpleNamespace(cycle_id=6, return_pct=0.7, benchmark_passed=True, proposal_bundle={}),
    ]

    summary = refresh_cycle_history_suggestion_effects(
        None,
        cycle_history=cycle_history,
    )

    assert summary["updated_bundle_count"] == 1
    assert summary["completed_effect_count"] == 1
    assert cycle_history[0].proposal_bundle["proposals"][0]["effect_status"] == "improved"


def test_candidate_builder_on_profitable_cycle_only_allows_safety_tightening(tmp_path: Path):
    config_path = _repo_model_config("momentum_v1.yaml")
    controller = SimpleNamespace(
        output_dir=tmp_path,
        model_name="momentum",
        model_config_path=config_path,
        auto_apply_mutation=False,
        current_params={"position_size": 0.2, "stop_loss_pct": 0.05},
        current_cycle_learning_proposals=[
            _proposal(
                "proposal_0009_001",
                source="optimization.research_feedback",
                patch={"position_size": 0.16},
                proposal_kind="runtime_param_adjustment",
                cycle_id=9,
            ),
            _proposal(
                "proposal_0009_002",
                source="review.param_adjustment",
                patch={"stop_loss_pct": 0.04},
                proposal_kind="param_adjustment",
                cycle_id=9,
            ),
            _proposal(
                "proposal_0009_003",
                source="optimization.llm_scoring",
                patch={"weights": {"change_5d": 0.25}},
                proposal_kind="scoring_adjustment",
                cycle_id=9,
            ),
        ],
        model_mutator=YamlConfigMutator(generations_dir=tmp_path / "generations"),
        cycle_history=[],
        _append_optimization_event=lambda event: None,
        _emit_module_log=lambda *args, **kwargs: None,
        _reload_investment_model=lambda path: None,
    )
    bundle = persist_cycle_proposal_bundle(
        controller,
        cycle_id=9,
        execution_snapshot={
            "active_config_ref": config_path,
            "active_version_id": "version_active_1",
            "runtime_fingerprint": "fingerprint_active_1",
            "model_name": "momentum",
            "runtime_overrides": {"position_size": 0.2, "stop_loss_pct": 0.05},
            "return_pct": 4.2,
            "is_profit": True,
            "benchmark_passed": True,
        },
    )

    event = build_cycle_candidate_from_proposals(
        controller,
        cycle_id=9,
        proposal_bundle=bundle,
        event_factory=Event,
        trigger_reason="cycle_review_completed",
    )
    payload = event.to_dict()
    candidate_path = Path(payload["decision"]["config_path"])
    generated = yaml.safe_load(candidate_path.read_text(encoding="utf-8"))

    assert payload["stage"] == "candidate_build"
    assert generated["params"]["stop_loss_pct"] == 0.04
    assert generated["params"]["position_size"] == 0.2
    assert generated["summary_scoring"]["weights"]["change_5d"] == 0.15
    gate = payload["evidence"]["proposal_gate"]
    assert gate["blocked_adjustments"]["params"]["position_size"] == 0.16
    assert "weights" in gate["blocked_adjustments"]["scoring"]
    assert gate["proposal_summary"]["blocked_proposal_count"] == 2
    assert gate["proposal_summary"]["approved_proposal_count"] == 1


def test_candidate_builder_rejects_single_step_identity_drift(tmp_path: Path):
    config_path = _repo_model_config("momentum_v1.yaml")
    controller = SimpleNamespace(
        output_dir=tmp_path,
        model_name="momentum",
        model_config_path=config_path,
        auto_apply_mutation=False,
        current_params={"position_size": 0.2},
        current_cycle_learning_proposals=[
            _proposal(
                "proposal_0010_001",
                source="optimization.llm_analysis",
                patch={"position_size": 0.1},
                proposal_kind="runtime_param_adjustment",
                cycle_id=10,
            ),
        ],
        model_mutator=YamlConfigMutator(generations_dir=tmp_path / "generations"),
        cycle_history=[],
        _append_optimization_event=lambda event: None,
        _emit_module_log=lambda *args, **kwargs: None,
        _reload_investment_model=lambda path: None,
    )
    bundle = persist_cycle_proposal_bundle(
        controller,
        cycle_id=10,
        execution_snapshot={
            "active_config_ref": config_path,
            "active_version_id": "version_active_1",
            "runtime_fingerprint": "fingerprint_active_1",
            "model_name": "momentum",
            "runtime_overrides": {"position_size": 0.2},
            "return_pct": -1.5,
            "is_profit": False,
        },
    )

    event = build_cycle_candidate_from_proposals(
        controller,
        cycle_id=10,
        proposal_bundle=bundle,
        event_factory=Event,
        trigger_reason="cycle_review_completed",
    )
    payload = event.to_dict()

    assert payload["stage"] == "candidate_build_skipped"
    assert payload["decision"]["skip_reason"] == "proposal_governance_rejected"
    assert payload["evidence"]["proposal_gate"]["violations"][0]["type"] == "single_step_identity_drift_exceeded"


def test_candidate_builder_rejects_cumulative_identity_drift(tmp_path: Path):
    root_config = _repo_model_config("momentum_v1.yaml")
    model_mutator = YamlConfigMutator(generations_dir=tmp_path / "generations")
    first_gen = model_mutator.mutate(
        root_config,
        param_adjustments={"position_size": 0.12},
        generation_label="cycle_0006",
    )
    active_config_path = str(first_gen["config_path"])
    controller = SimpleNamespace(
        output_dir=tmp_path,
        model_name="momentum",
        model_config_path=active_config_path,
        auto_apply_mutation=False,
        current_params={"position_size": 0.12},
        current_cycle_learning_proposals=[
            _proposal(
                "proposal_0011_001",
                source="review.param_adjustment",
                patch={"position_size": 0.08},
                proposal_kind="param_adjustment",
                cycle_id=11,
            ),
        ],
        model_mutator=model_mutator,
        cycle_history=[],
        _append_optimization_event=lambda event: None,
        _emit_module_log=lambda *args, **kwargs: None,
        _reload_investment_model=lambda path: None,
    )
    bundle = persist_cycle_proposal_bundle(
        controller,
        cycle_id=11,
        execution_snapshot={
            "active_config_ref": active_config_path,
            "active_version_id": "version_active_2",
            "runtime_fingerprint": "fingerprint_active_2",
            "model_name": "momentum",
            "runtime_overrides": {"position_size": 0.12},
            "return_pct": -0.8,
            "is_profit": False,
        },
    )

    event = build_cycle_candidate_from_proposals(
        controller,
        cycle_id=11,
        proposal_bundle=bundle,
        event_factory=Event,
        trigger_reason="cycle_review_completed",
    )
    payload = event.to_dict()
    gate = payload["evidence"]["proposal_gate"]

    assert payload["stage"] == "candidate_build_skipped"
    assert gate["violations"][0]["type"] == "cumulative_identity_drift_exceeded"
    assert gate["baseline"]["config_ref"].endswith("momentum_v1.yaml")


def test_candidate_builder_allows_small_scoring_identity_shift_within_budget(tmp_path: Path):
    config_path = _repo_model_config("momentum_v1.yaml")
    controller = SimpleNamespace(
        output_dir=tmp_path,
        model_name="momentum",
        model_config_path=config_path,
        auto_apply_mutation=False,
        current_params={"position_size": 0.2},
        current_cycle_learning_proposals=[
            _proposal(
                "proposal_0012_001",
                source="optimization.llm_scoring",
                patch={"weights": {"change_5d": 0.18}},
                proposal_kind="scoring_adjustment",
                cycle_id=12,
            ),
        ],
        model_mutator=YamlConfigMutator(generations_dir=tmp_path / "generations"),
        cycle_history=[],
        _append_optimization_event=lambda event: None,
        _emit_module_log=lambda *args, **kwargs: None,
        _reload_investment_model=lambda path: None,
    )
    bundle = persist_cycle_proposal_bundle(
        controller,
        cycle_id=12,
        execution_snapshot={
            "active_config_ref": config_path,
            "active_version_id": "version_active_1",
            "runtime_fingerprint": "fingerprint_active_1",
            "model_name": "momentum",
            "return_pct": -0.4,
            "is_profit": False,
        },
    )

    event = build_cycle_candidate_from_proposals(
        controller,
        cycle_id=12,
        proposal_bundle=bundle,
        event_factory=Event,
        trigger_reason="cycle_review_completed",
    )
    payload = event.to_dict()
    candidate_path = Path(payload["decision"]["config_path"])
    generated = yaml.safe_load(candidate_path.read_text(encoding="utf-8"))
    gate = payload["evidence"]["proposal_gate"]

    assert payload["stage"] == "candidate_build"
    assert generated["summary_scoring"]["weights"]["change_5d"] == 0.18
    assert gate["drift_summary"]["approved_scoring"]["weights.change_5d"]["candidate_drift_ratio_vs_baseline"] == pytest.approx(0.2)
    assert gate["proposal_summary"]["blocked_proposal_count"] == 0


def test_candidate_builder_rejects_cumulative_scoring_identity_drift(tmp_path: Path):
    root_config = _repo_model_config("momentum_v1.yaml")
    model_mutator = YamlConfigMutator(generations_dir=tmp_path / "generations")
    first_gen = model_mutator.mutate(
        root_config,
        scoring_adjustments={"weights": {"change_5d": 0.21}},
        generation_label="cycle_0012",
    )
    active_config_path = str(first_gen["config_path"])
    controller = SimpleNamespace(
        output_dir=tmp_path,
        model_name="momentum",
        model_config_path=active_config_path,
        auto_apply_mutation=False,
        current_params={"position_size": 0.2},
        current_cycle_learning_proposals=[
            _proposal(
                "proposal_0013_001",
                source="optimization.llm_scoring",
                patch={"weights": {"change_5d": 0.24}},
                proposal_kind="scoring_adjustment",
                cycle_id=13,
            ),
        ],
        model_mutator=model_mutator,
        cycle_history=[],
        _append_optimization_event=lambda event: None,
        _emit_module_log=lambda *args, **kwargs: None,
        _reload_investment_model=lambda path: None,
    )
    bundle = persist_cycle_proposal_bundle(
        controller,
        cycle_id=13,
        execution_snapshot={
            "active_config_ref": active_config_path,
            "active_version_id": "version_active_3",
            "runtime_fingerprint": "fingerprint_active_3",
            "model_name": "momentum",
            "return_pct": -1.1,
            "is_profit": False,
        },
    )

    event = build_cycle_candidate_from_proposals(
        controller,
        cycle_id=13,
        proposal_bundle=bundle,
        event_factory=Event,
        trigger_reason="cycle_review_completed",
    )
    payload = event.to_dict()
    gate = payload["evidence"]["proposal_gate"]

    assert payload["stage"] == "candidate_build_skipped"
    assert gate["violations"][0]["type"] == "cumulative_scoring_identity_drift_exceeded"
    assert gate["baseline"]["config_ref"].endswith("momentum_v1.yaml")


def test_candidate_builder_allows_small_agent_weight_shift_within_budget(tmp_path: Path):
    config_path = _repo_model_config("momentum_v1.yaml")
    controller = SimpleNamespace(
        output_dir=tmp_path,
        model_name="momentum",
        model_config_path=config_path,
        auto_apply_mutation=False,
        current_params={"position_size": 0.2},
        current_cycle_learning_proposals=[
            _proposal(
                "proposal_0014_001",
                source="review.agent_weight_adjustment",
                patch={"trend_hunter": 1.2},
                proposal_kind="agent_weight_adjustment",
                cycle_id=14,
            ),
        ],
        model_mutator=YamlConfigMutator(generations_dir=tmp_path / "generations"),
        cycle_history=[],
        _append_optimization_event=lambda event: None,
        _emit_module_log=lambda *args, **kwargs: None,
        _reload_investment_model=lambda path: None,
    )
    bundle = persist_cycle_proposal_bundle(
        controller,
        cycle_id=14,
        execution_snapshot={
            "active_config_ref": config_path,
            "active_version_id": "version_active_1",
            "runtime_fingerprint": "fingerprint_active_1",
            "model_name": "momentum",
            "return_pct": -0.2,
            "is_profit": False,
        },
    )

    event = build_cycle_candidate_from_proposals(
        controller,
        cycle_id=14,
        proposal_bundle=bundle,
        event_factory=Event,
        trigger_reason="cycle_review_completed",
    )
    payload = event.to_dict()
    candidate_path = Path(payload["decision"]["config_path"])
    generated = yaml.safe_load(candidate_path.read_text(encoding="utf-8"))
    gate = payload["evidence"]["proposal_gate"]

    assert payload["stage"] == "candidate_build"
    assert generated["agent_weights"]["trend_hunter"] == 1.2
    assert gate["drift_summary"]["approved_agent_weights"]["trend_hunter"]["candidate_drift_ratio_vs_baseline"] == pytest.approx(0.2)
    assert gate["proposal_summary"]["blocked_proposal_count"] == 0


def test_candidate_builder_rejects_cumulative_agent_weight_identity_drift(tmp_path: Path):
    root_config = _repo_model_config("momentum_v1.yaml")
    model_mutator = YamlConfigMutator(generations_dir=tmp_path / "generations")
    first_gen = model_mutator.mutate(
        root_config,
        agent_weight_adjustments={"trend_hunter": 1.4},
        generation_label="cycle_0014",
    )
    active_config_path = str(first_gen["config_path"])
    controller = SimpleNamespace(
        output_dir=tmp_path,
        model_name="momentum",
        model_config_path=active_config_path,
        auto_apply_mutation=False,
        current_params={"position_size": 0.2},
        current_cycle_learning_proposals=[
            _proposal(
                "proposal_0015_001",
                source="review.agent_weight_adjustment",
                patch={"trend_hunter": 1.6},
                proposal_kind="agent_weight_adjustment",
                cycle_id=15,
            ),
        ],
        model_mutator=model_mutator,
        cycle_history=[],
        _append_optimization_event=lambda event: None,
        _emit_module_log=lambda *args, **kwargs: None,
        _reload_investment_model=lambda path: None,
    )
    bundle = persist_cycle_proposal_bundle(
        controller,
        cycle_id=15,
        execution_snapshot={
            "active_config_ref": active_config_path,
            "active_version_id": "version_active_4",
            "runtime_fingerprint": "fingerprint_active_4",
            "model_name": "momentum",
            "return_pct": -0.9,
            "is_profit": False,
        },
    )

    event = build_cycle_candidate_from_proposals(
        controller,
        cycle_id=15,
        proposal_bundle=bundle,
        event_factory=Event,
        trigger_reason="cycle_review_completed",
    )
    payload = event.to_dict()
    gate = payload["evidence"]["proposal_gate"]

    assert payload["stage"] == "candidate_build_skipped"
    assert gate["violations"][0]["type"] == "cumulative_agent_weights_identity_drift_exceeded"
    assert gate["baseline"]["config_ref"].endswith("momentum_v1.yaml")
